### PR TITLE
Fix Style/ModuleFunction offenses

### PR DESCRIPTION
**Pull request by magni-**
From #752

### CODE REVIEW

**Comment by jaredbeck** [comment]
Do the methods in these serializer modules really need to be instance methods and module methods at the same time? That seems like a poor design (not your fault, obviously). If we can settle on just instance methods, or just module methods, that would be my preference.

**Comment by magni-** [comment]
TBH I haven't really looked into where those methods were being used. I'll take a look today.

**Comment by magni-** [comment]
https://github.com/airblade/paper_trail/pull/196 seems to be where the dual module/instance use comes from.

**Comment by jaredbeck** [comment]
>> Do the methods in these serializer modules really need to be instance methods and module methods at the same time?
>
> #196 seems to be where the dual module/instance use comes from.

I see, there was an actual use case for this. In that case, the design is justified and I'm fine with this PR as is. However @batter might prefer to keep the `extend self`, since he's the one who wrote that line. I'll let him decide what to do with this PR.

**Comment by jaredbeck** [comment]
Hmmm. I looked into this a bit more, and this seems to be a breaking change, because `module_function` makes them private.

```ruby
# `extend self` makes the copies public
module Pub
  extend self
  def x; end
end

class PubClass
  include Pub
end

PubClass.new.x #=> nil

# `module_function` makes the copies public
module Priv
  def x; end
  module_function :x
end

class PrivClass
  include Priv
end

PrivClass.new.x
# NoMethodError: private method `x' called for #<PrivClass:0x007fba1c0e7e90>
```

**Comment by magni-** [comment]
Ooh interesting, I did not think about that behavior. What do you think the best course of action is here?

**Comment by jaredbeck** [comment]
Closed by 3b73566ef78162e71ff2fcd144ace2aa2e8e4522

I asked for clarification about this at https://github.com/bbatsov/ruby-style-guide/issues/556

**Pull request closed without merging**
