### PR TITLE
In MySQL, use longtext instead of text

### LINKED ISSUE #248: Big objects
currently migration is like the following:

```ruby
class CreateVersions < ActiveRecord::Migration
  def self.up
    create_table :versions do |t|
      t.string   :item_type, :null => false
      t.integer  :item_id,   :null => false
      t.string   :event,     :null => false
      t.string   :whodunnit
      t.text     :object
      t.datetime :created_at
    end
    add_index :versions, [:item_type, :item_id]
  end

  def self.down
    remove_index :versions, [:item_type, :item_id]
    drop_table :versions
  end
end
```

This approach is good enough for objects that serialized is smaller then 64kb (on mysql), as this is the maximum size "TEXT" can hold, according to http://www.electrictoolbox.com/maximum-length-mysql-text-field-types/

I've searched on how to force ActiveRecord migration to create "MEDIUMTEXT" or "LONGTEXT". It seems that all you have to do is define a limit that is bigger enough.

See http://stackoverflow.com/questions/4443477/rails-3-migration-with-longtext for more information.

I don't know what is the best default versions should have. It seems like a good idea to have a bigger size as default to prevent headaches from people who figure out late that they lost data because it wasn't saved (as the object was bigger then expected). Also worth noting that it increases only 2 bytes per entry according to: http://dev.mysql.com/doc/refman/5.0/en/storage-requirements.html#id733892

This might be the reason #245 happened.

### PR DESCRIPTION
**Pull request by jaredbeck**
See discussion in https://github.com/airblade/paper_trail/issues/248

### CODE REVIEW

**Comment by batter** [comment]
Seems fine to me, and could potentially even be backported to v3.x, however, I wonder if we should just add this as a suggestion instead of a default?  In [your comment on 248](https://github.com/airblade/paper_trail/issues/248#issuecomment-114282740), you mention that:

> `text` uses two bytes to store its length, `mediumtext` uses three, and `longtext` uses four. Otherwise I'm not seeing any downside.

I don't think those are big enough size differences to prevent this from merging, although for an app with millions of rows, perhaps this would have big ramifications.  Users that know what they are doing can always take off the limit declaration. Then again they could also add it prior to this. So it's kind of a tossup, but I'll let you use your judgement as to what you feel makes the most sense.

I will say that I have been wondering for a while whether it makes sense to switch the default serializer to `PaperTrail::Serializers::JSON` (instead of `PaperTrail::Serializers::YAML`), because JSON syntax is more consistent in it's parsing (not as much of an issue anymore, but when it was unclear whether you'd get `syck` or `psych` depending on which Ruby version you were using for a while, it did cause some compatibility issues), and also dumps into shorter and more concise syntax than YAML (it's also faster as far as I know).  This would probably prevent some of these column limit size issues that people like @brodock were running up against. That being said, it would also be a breaking change for anyone who didn't read the documentation and realize they needed to manually swap in the old YAML serializer if they have legacy data (or update all their old data to JSON... perhaps we could provide a script / mechanism).

There is some appropriate / notable discussion about the pros / cons of JSON vs YAML in #194 & a bit of commentary on #504. There was also a user submitted script for updating legacy YAML data to JSON that we might be able to leverage in #388..  Since it's a non backwards compatible change, if we do decide to go this route, it would probably need to be part of a major version release.

**Comment by jaredbeck** [comment]
> I wonder if we should just add this as a suggestion instead of a default?

I'm undecided.  On one hand, it's really easy to increase the size of the object column later if you hit the 64k limit that Gabriel hit in https://github.com/airblade/paper_trail/issues/248.  On the other hand, as Gabriel pointed out, 

> It seems like a good idea to have a bigger size as default to prevent headaches from people who figure out late that they lost data because it wasn't saved

That's hard to argue with, and we're only talking about 2-4 bytes per row.  Even with millions of rows, that's still only megabytes.

If you leave it up to me, I'll probably merge this, but I could be persuaded either way. :)

> I will say that I have been wondering for a while whether it makes sense to switch the default serializer to PaperTrail::Serializers::JSON (instead of PaperTrail::Serializers::YAML)

Interesting.  While I've worked with both formats for years, I can't say I've given them enough scrutiny to say which would be better for PaperTrail.  Of course, if you're using a modern postgres that supports json columns, it'd be a shame not to use that with PaperTrail.

**Comment by batter** [comment]
> That's hard to argue with, and we're only talking about 2-4 bytes per row. Even with millions of rows, that's still only megabytes.

That's an excellent point, I say we merge it.

**Comment by carsonreinke** [comment]
It should be noted that MySQL will silently trim off excess bytes with these BLOB fields, making the format unreadable after.  Making the default bigger is probably the best idea.

**Pull request merged**
