### PR TITLE
Add note about location of 'has_paper_trail' in class

### PR DESCRIPTION
**Pull request by radionewzealand**
Paper trail can clash with other callbacks if it is not called first in the class.

Refer to: http://stackoverflow.com/questions/32417619/tests-fail-with-has-paper-trail

### CODE REVIEW

**Comment by jaredbeck** [comment]
```diff
+# has_paper-trail should be placed at the top of the class declaration (before any other code)
+# as it needs to register its callbacks first.
```

This statement is not true of all applications.

A better statement would be "has_paper-trail installs a number of callbacks.  If there are other callbacks in your model, be aware of any potential interactions.  The order of callbacks may matter."

In the future, where appropriate, you can add `[ci skip]` to your commit messages to skip the test run.

**Comment by jaredbeck** [comment]
Closed via 64c4a5b

**Comment by radionewzealand** [comment]
OK, thanks for the feedback and not about CI. You want me to create a new PR?

**Comment by jaredbeck** [comment]
> You want me to create a new PR?

No need, unless you think https://github.com/airblade/paper_trail/commit/64c4a5bbe992ee048900ca7152296fedabe91045 doesn't explain it.

**Comment by radionewzealand** [comment]
Looks good to me. Cheers!

**Pull request closed without merging**
