### PR TITLE
Versioning a model that has a polymorphic belongs_to association

### PR DESCRIPTION
**Pull request by kaapa**
New association versioning feature is broken for polymorphic belongs_to associations as reflection has no way to point to the dynamically set [associated model class](https://github.com/kaapa/paper_trail/compare/polymorphic_belongs_to_association?expand=1#diff-7fc294d950a7311cf6ad815a91f90ac2L376).

These commits add a failing test case and a "fix" by disabling the feature for polymorphic associations.

### CODE REVIEW

**Comment by batter** [comment]
Hmm.... Any ideas of how we might be able to make this work instead of just ignoring those associations? @bli?

**Comment by kaapa** [comment]
Unfortunately I don't think I'm able to take this much further at this time or in the immediate future as I'm a bit time constrained right now... :(

Perhaps this could be merged as an intermediate fix en route to full support for polymorphic associations?

PS. At a glance Travis test failure seems unrelated to this patch. Is that correct? Also perhaps a mention about polymorphic association behavior in the readme's Associations section should be added whether or not this patch gets merged.

**Comment by batter** [comment]
Travis is failing because I have a few tests I created to test my feature implementation for #420 (`where_object_changes` method implementation) which seem to have inconsistent return values on certain versions of Ruby, so I need to fix those myself. Going to try to do that later today, but anyways, you are correct that the failures are unrelated to this.

**Comment by batter** [comment]
Just to follow up @mhuggins was able to fix the polymorphic association versioning for even `belongs_to` associations with the work he did in #476. Thanks for the PR though.

**Comment by mhuggins** [comment]
@batter I didn't consider writing a test that covers polymorphic `belongs_to` associations, only `has_many` associations.  It's probably worth adding a test that covers that though, and perhaps `has_one` associations as well!

**Pull request closed without merging**
