### PR TITLE
Added instructions for use with Rails Admin.

### PR DESCRIPTION
**Pull request by piratebroadcast**
Throws an error otherwise.

### CODE REVIEW

**Comment by seanlinsley** [comment]
For context: #707

**Comment by jaredbeck** [comment]
Does `rails_admin` actually require `--with-associations` or is this just a workaround?

**Comment by piratebroadcast** [comment]
Throws errors without --with-associations, papertrail and railsadmin
unusable without the --with-associations command.

On Sun, Feb 21, 2016 at 1:37 PM, Jared Beck <notifications@github.com>
wrote:

> Does rails_admin actually require --with-associations or is this just a
> workaround?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airblade/paper_trail/pull/716#issuecomment-186882998>.
>



-- 
Jesse Waites
JesseWaites.com

**Comment by jaredbeck** [comment]
Interestingly, it looks like the [rails admin test suite][1] only tests against `paper_trail ~> 3.0`.

PaperTrail is designed to work without tracking associations. In fact, tracking associations is an experimental feature with known issues. So, telling people to turn on associations tracking is not my preferred solution. 

However, I'm inclined to document this workaround anyway, because I think a good chunk of paper trail users are rails admin users (10-20% maybe) and because Jesse (@piratebroadcast) is [not the first to suggest this workaround][2]. 

[1]: https://github.com/sferik/rails_admin/blob/master/gemfiles/rails_4.2.gemfile#L12
[2]: https://github.com/sferik/rails_admin/issues/2405

**Pull request merged**
