### PR TITLE
Format comments

### PR DESCRIPTION
**Pull request by jaredbeck**
- Wrap comments at 80 chars
- Fix English grammar
  - Start sentances with capital letters
  - End sentances with a period
- Use markdown for lists, e.g. method arguments

[ci skip]

### CODE REVIEW

**Comment by jaredbeck** [comment]
I've got another, more important, PR that depends on these changes, so I'll go ahead and merge this to avoid any conflicts.  I don't think there's anything too controversial in formatting comments, but let me know if you see something you don't like and we can revert it.

**Comment by batter** [comment]
Man that's a lot of comment refactoring! Did you do that yourself or use a tool?

**Comment by jaredbeck** [comment]
I wish there were a comprehensive tool for this.  The English grammar and markdown lists were manual. For the hard wrap I use the "Wrap to Column" plugin for RubyMine.

**Comment by batter** [comment]
I'm likely to blame for a lot of the comments not being wrapped at 80 characters. I realize now that it is a convention amongst many developers, especially those who like to develop on emacs and vim with multiple panes in a single session, however, I didn't realize that until a year or two ago, and definitely blatantly went over that number generously on many occasions.

In terms of capitalization ¯\_(ツ)_/¯, it's comments

**Pull request merged**
