### PR TITLE
Make whodunnit column configurable

### PR DESCRIPTION
**Pull request by juliankrispel**
Hey there.

We're using paper_trail and want to rename the whodunnit column to match our conventions so I made this configurable.

Not sure where to add specs for this since there seem to be two different spec folders. Please advise.

### CODE REVIEW

**Comment by batter** [comment]
So this is just a way to enable the user to rename the field on the versions table to something other than `whodunnit`?

**Comment by juliankrispel** [comment]
@batter exactly, similar to how the `timestamp_field` works

**Comment by jaredbeck** [comment]
All tests failing. Please fix, then squash your commits. Thanks.

**Comment by juliankrispel** [comment]
Will do cheers

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co

**Comment by gr8bit** [comment]
:+1:

**Comment by jaredbeck** [comment]
>> All tests failing. Please fix, then squash your commits. Thanks. (15 days ago)
> Will do (15 days ago)

Closing due to lack of activity, will reopen if activity resumes.

**Pull request closed without merging**
