### PR TITLE
clarify the issue with `where_object_changes` for numeric values

### PR DESCRIPTION
**Pull request by sergey-alekseev**
History
---
[The first problem mention](https://github.com/airblade/paper_trail/commit/1ad78383aa58d6b74e237f84310f7440712710ab).
[The major issue](https://github.com/airblade/paper_trail/issues/803) with relevant discussions.

Details
---
I see the problem only with one specific case – when the method is `where_object_changes` and the serializer is YAML. Which is a default configuration.

I see there are 6 types of queries with a numeric value for `where_object_changes` and `where_object` (grabbed from `version_spec.rb`):
```sql
# where_object_changes
# 1
SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = 1 AND "versions"."item_type" = 'Widget' AND (object_changes @> '{"an_integer":[1]}')  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC

# 2
SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = 1 AND "versions"."item_type" = 'Widget' AND ("versions"."object_changes" ILIKE '%
an_integer:
- 1
%' OR "versions"."object_changes" ILIKE '%
an_integer:
-%
- 1
%')  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC

# 3
SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = 1 AND "versions"."item_type" = 'Widget' AND (((object_changes->>'an_integer' ILIKE '[1,%') OR (object_changes->>'an_integer' ILIKE '[%,1]%')))  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC

# where_object
# 4
SELECT "versions".* FROM "versions" WHERE (object @> '{"an_integer":1}')

# 5
SELECT "versions".* FROM "versions" WHERE (object->>'an_integer' = '1')

# 6
SELECT "versions".* FROM "versions" WHERE ("versions"."object" ILIKE '%
an_integer: 1
%')
```

The only problematic one is `#2`. It incorrectly matches `object_changes` like
```yaml
---
name:
-
- Kimberli
an_integer:
-
- 0
created_at:
-
- 2017-09-28 18:30:13.369889000 Z
updated_at:
-
- 2017-09-28 18:30:13.369889000 Z
id:
-
- 1
---
name:
- foobar
- Hayes
an_integer:
- 77
- 1
updated_at:
- 2017-09-28 18:30:13.383966000 Z
- 2017-09-28 18:30:13.395539000 Z
```

@batter @jaredbeck correct me if I'm wrong.

### CODE REVIEW

**Comment by jaredbeck** [comment]
Hi Sergey, Thanks for the contribution!

It sounds like where_object_changes+YAML has the same issue as where_object_changes+JSON-in-text-column, as described in https://github.com/airblade/paper_trail/issues/803. I think the same solution (https://github.com/airblade/paper_trail/pull/993) would be appropriate here. 

What do you think?

**Comment by jaredbeck** [comment]
> It sounds like where_object_changes+YAML has the same issue as where_object_changes+JSON-in-text-column, as described in #803. I think the same solution (#993) would be appropriate here.

To clarify, I am suggesting that we raise an error when someone is storing YAML in a `text` column and they call `where_object_changes`. Sound good?

**Comment by sergey-alekseev** [comment]
@jaredbeck I think applying a "solution" like #979 + #993 is better than not applying it.  

Ideally such cases should be fixed, but I'm not interested in a text column.  

---
FYI I fixed a failed spec example by changing   
```ruby
let(:int) { column_datatype_override ? 1 : rand(5) + 1 }
```

to
```ruby
let(:int) { column_datatype_override ? 1 : rand(5) + 2 }
```

Initially I didn't take into account `rand(5) + 1` may return 1 :flushed:

**Comment by jaredbeck** [comment]
>> It sounds like where_object_changes+YAML has the same issue as where_object_changes+JSON-in-text-column, as described in #803. I think the same solution (#993) would be appropriate here.

>> To clarify, I am suggesting that we raise an error when someone is storing YAML in a `text` column and they call `where_object_changes`. Sound good?

> @jaredbeck I think applying a "solution" like #979 + #993 is better than not applying it.

OK, raising an error is a breaking change, so we should start with a deprecation warning , just like we did in #979. If you agree, will you please add such a warning, Sergey? Thanks!

**Comment by sergey-alekseev** [comment]
@jaredbeck I added a deprecation warning. Let me know if you think commits should be squashed.

**Comment by jaredbeck** [comment]
Looks perfect! Thanks Sergey.

**Comment by jaredbeck** [comment]
We'll wait a few months after this deprecation warning is released to give people a chance to discuss the issue here. Then, if no concerns are raised we will replace the warning with an error.

**Pull request merged**
