### PR TITLE
Organize association reification methods

### PR DESCRIPTION
**Pull request by jaredbeck**
🗄 📁 📄 📄 📄 📄 📄

### CODE REVIEW

**Comment by jaredbeck** [comment]
What do you think, Ben?

This breaks up the giant `Reifier` into the following modules. 

- reifiers/has_and_belongs_to_many
- reifiers/has_many_through
- reifiers/has_many
- reifiers/belongs_to
- reifiers/has_one

These modules are surprisingly independent. The only two that share any code are `has_many` and `has_many_through`.

I've chosen to continue the same "stateless module" design of `Reifier`. The new modules are not "mixed into" any other class, they just have module methods. It's a very FP style, and I think it works fine here.

This PR improves the codeclimate score of `Reifier` from "F" to "D". (https://codeclimate.com/github/airblade/paper_trail/compare/organizing_assoc_reifiers#ratings)

**Comment by batter** [comment]
I like the idea of making things more modular, and I also like the FP style approach, I'd like to take a little bit of a closer look when I have some more time over the next week or two, but it looks good on the surface. It would be good for me to go through this more closely since I'm less familiar with a lot of the association reification code than I am with other parts of the codebase.

**Comment by batter** [comment]
@jaredbeck - I was on the Amtrak back to NY tonight and spent a bit of time doing some initial code review on this PR. I want to spend some more time reviewing this since there's a lot going on. Most of the feedback I gave thus far is small questions about syntax. I intend to give a more thorough and thoughtful review soon.

**Comment by jaredbeck** [comment]
> I intend to give a more thorough and thoughtful review soon.

Thanks Ben, I'll look forward to it.

**Comment by batter** [comment]
Apologies, I came down with a nasty cold that's kept me out of action the last few days, will try to wrap up my review by end of week.

**Comment by jaredbeck** [comment]
> Apologies, I came down with a nasty cold ..

No worries. I got one last week. Feel better.

**Comment by jaredbeck** [comment]
Ben, I'm going to go ahead and merge this. If you do get around to reviewing it, I will look forward to your feedback then, thanks.

**Pull request merged**
