### PR TITLE
Add note in readme about conditional procs

### PR DESCRIPTION
**Pull request by gamov**
Ref. issue: https://github.com/airblade/paper_trail/issues/656

### CODE REVIEW

**Comment by jaredbeck** [comment]
Please squash your commits and remove the italics, thanks.

**Comment by jaredbeck** [comment]
Closed by 3e7f5a1bfb42c523d12db6ef89a3c6891502a602

Thanks!

**Comment by gamov** [comment]
Sorry @jaredbeck, I didn't follow up timely. We just had a daughter and things went in emergency mode for a while..

**Comment by jaredbeck** [comment]
No worries. Congratulations! :D

**Pull request closed without merging**
