### PR TITLE
Check connection to database is present for validating table existence.

### PR DESCRIPTION
**Pull request by josisusan**
Check if database connection is present before validation of table existence.

### CODE REVIEW

**Comment by jaredbeck** [comment]
I think `NoDatabaseError` was added in rails 4, but we want PT to still support rails 3.

**Comment by batter** [comment]
I need to look into this but it would be splendid if there was a simple way
to just check ActiveRecord::Base.connection_established? Or something to
that effect

**Comment by jaredbeck** [comment]
> I need to look into this but it would be splendid if there was a simple way to just check ActiveRecord::Base.connection_established? Or something to that effect

There is `ActiveRecord::ConnectionHandling.connected?`.

```
ActiveRecord::Base.connected? # => true
PaperTrail::Version.connected? # => true
```

**Comment by seanlinsley** [comment]
It seems possible that there could be no existing database connection, but a completely valid database.

**Comment by Bivek** [comment]
Yes, unless you don't make the real connection, `conntected?` will always be false

**Comment by josisusan** [comment]
@jaredbeck I have tried using PaperTrail::Version.connected? but it gives false like @Bivek have mentioned.

**Comment by batter** [comment]
@josisusan and @jaredbeck - that is the problem with `#connected?`, it will return `false` if you have not made a query against the table within a current session. That seems like unexpected behavior to me but is how it works currently as far as I understand.

**Comment by jaredbeck** [comment]
I thought we couldn't use `NoDatabaseError` because we still support rails 3, but interestingly, having an undefined constant in a `rescue` does not cause a `NameError`.

```
puts "interesting" rescue ConstantThatDoesNotExist # no `NameError`
```

So, I guess we could use `NoDatabaseError` if we had to, even though it won't help rails 3 users. I'd be OK with that.

Susan, can you rebase please?

**Comment by josisusan** [comment]
We (with @Bivek) are figuring out some alternatives to support rails 3 with snippets below:
```ruby
begin
  PaperTrail::VersionAssociation.table_exists?
rescue => error
  case error.class.to_s
  when "::PG::Error", "PG::ConnectionBad"
     error.message.include?("does not exist") ? false : raise(error)
  when "Mysql2::Error"
    ...
  when "ActiveRecord::NoDatabaseError"
    false
 ...
```

**Comment by jaredbeck** [comment]
It's funny how big this method has grown. Originally it was just the `table_exists?` I think :grin:

**Comment by jaredbeck** [comment]
> We (with @Bivek) are figuring out some alternatives to support rails 3 ..

Btw if you want to run the tests against rails 3 locally, you can use `bundle exec appraisal ar3 rake`. See the [Contributing Guide][1] for more tips.

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md

**Comment by seanlinsley** [comment]
Why do we want this behavior in the first place? I think it would have been fine to keep the behavior we had before #465 (only raising an error once something else tries accessing the versions table).

I go into more detail here: https://github.com/airblade/paper_trail/issues/740#issuecomment-202702068

**Comment by jaredbeck** [comment]
> Why do we want this behavior in the first place? I think it would have been fine to keep the behavior we had before #465 (only raising an error once something else tries accessing the versions table).

For backwards compatibility, we don't want to require people to have the `versions_associations` table. If we required everyone to have the `versions_associations` table, we might not need *any* of this complexity. It's a tempting solution :smiling_imp:

**Comment by jaredbeck** [comment]
> I think it would have been fine to keep the behavior we had before #465 (only raising an error once something else tries accessing the versions table

@seanlinsley can you put together a PR for that so we can compare? Thanks.

**Comment by jaredbeck** [comment]
Another alternative is to require users to configure this. Susan, Sean, Ben, please take a look at https://github.com/airblade/paper_trail/pull/785, thanks.

**Comment by jaredbeck** [comment]
Closed by https://github.com/airblade/paper_trail/pull/785

Thanks Susan, Bardan, Sean, and Ben!

**Pull request closed without merging**
