### PR TITLE
add actor method to actually retrieve an object

### PR DESCRIPTION
**Pull request by ankit1910**

### CODE REVIEW

**Comment by batter** [comment]
Global ID is not a dependency for the gem currently, and I don't think we want to support it. If someone wants to use this kind of setup then I encourage them to do so, however, the current infrastructure will allow them to do so without having to add it in as a primary function of the gem.

If we were going to consider this, at the least, we would want to add the global id gem as a gem dependency.

**Comment by jaredbeck** [comment]
Hi Ankit, neat idea, but I think I agree with Ben.

> Global ID .. I don't think we want to support it.  .. the current infrastructure will allow them to do so without having to add it in as a primary function of [PaperTrail].

If you think a lot of people will use this feature, I'd encourage you to make a gem named `paper_trail-globalid` that does this. If you do, I'd be happy to link to it from the PaperTrail documentation.

**Comment by aditya-kapoor** [comment]
@ankit1910 :+1: on the idea...lets collaborate on making a library which does that...

**Comment by ankit1910** [comment]
Thanks for your support :)"https://github.com/ankit1910/paper_trail_globalid"

**Comment by jaredbeck** [comment]
According to [rubygems naming conventions][1], the correct name for the gem is `paper_trail-globalid` .

> Use dashes for extensions
>
> If you’re adding functionality to another gem, use a dash.

[1]: http://guides.rubygems.org/name-your-gem/

**Comment by jaredbeck** [comment]
Let me know when you release a stable (non-rc) version and I'll add a link to our readme.

**Comment by ankit1910** [comment]
Hi @jaredbeck 
you can check the latest code here "https://github.com/ankit1910/paper_trail-globalid".

**Comment by jaredbeck** [comment]
Awesome, thanks Ankit! Where would be a good place to mention it in our readme?

**Comment by ankit1910** [comment]
Hi @jaredbeck
I feel we could make a new section under "Finding Out Who Was Responsible For A Change" named as ‘Storing Actual object using globalid’ that refers to the gem and demonstrates how to use it.

  I would gladly raise a PR for this if you like :)

**Comment by jaredbeck** [comment]
> we could make a new section under "Finding Out Who Was Responsible For A Change" named as ‘Storing Actual object using globalid’ that refers to the gem and demonstrates how to use it.
>

That sounds like a good place. Please keep it brief though. Detailed usage instructions should live in your README.
 
>   I would gladly raise a PR for this if you like :)

Great! Thanks.

**Comment by ankit1910** [comment]
@jaredbeck: https://github.com/airblade/paper_trail/pull/709

:)

**Pull request closed without merging**
